# ############################################################ #
# 
# BasicBukkit - Basic commands for any new MineCraft server
# Copyright 2011 Core S2 - See License.txt for info
# 
# This source file is developed and maintained by:
# + Jeremy Bridon jbridon@cores2.com
# 
# File: config.yml
# Desc: Basic Bukkit's default configuration file.
# 
# ############################################################ #

# Message of the Day
motd:
    - "Welcome to a BasicBukkit server! V1.1"
    - "&aPlease type /help for a list of commands"
    - "&aFound a bug? Report it at: code.google.com/p/basicbukkit"

# Op groups
# Note that groups should ALWAYS be numbered 0, 1, 2, ....
groups:
    
    # Guest group (can do nothing except observe)
    - id: 0
      name: Guest
      pre: "&7Guest"
      commands:
          - help
          - motd
          - clear
          - who
          - where
          - home
          - sethome
          - protectinfo
          - afk
          - msg
          - pm
      banned_access: false
      build: false
      worldedit: false
    
    # Trial group (can do simple building)
    - id: 1
      name: Trial
      pre: "&8Trial"
      commands:
          - help
          - motd
          - clear
          - who
          - where
          - home
          - sethome
          - protectinfo
          - afk
          - msg
          - pm
          - god
          - pvp
          - kit
          - vote
          - lock
          - unlock
      banned_access: false
      build: true
      worldedit: false
    
    # Builder group (trusted)
    - id: 2
      name: Builder
      pre: "&bBuilder"
      commands:
          - god
          - pvp
          - help
          - motd
          - clear
          - who
          - where
          - tp
          - warp
          - jump
          - list
          - setwarp
          - delwarp
          - kit
          - item
          - i
          - clean
          - cleanall
          - home
          - sethome
          - protectinfo
          - afk
          - msg
          - pm
          - top
          - vkick
          - vban
          - vote
          - lock
          - unlock
      banned_access: false
      build: true
      worldedit: false
    
    # Moderator group
    - id: 3
      name: Mod
      pre: "&9Mod"
      commands:
          - god
          - pvp
          - help
          - motd
          - clear
          - who
          - where
          - kick
          - ban
          - unban
          - unkick
          - who
          - time
          - weather
          - kit
          - item
          - i
          - give
          - clean
          - op
          - kill
          - say
          - tp
          - warp
          - jump
          - list
          - setwarp
          - delwarp
          - home
          - sethome
          - protectinfo
          - afk
          - msg
          - pm
          - spawn
          - top
          - p1
          - p2
          - protect
          - protectpvp
          - protectadd
          - protectrem
          - protectdel
          - mute
          - scout
          - vkick
          - vban
          - vote
          - lock
          - unlock
      banned_access: false
      build: true
      worldedit: false
    
    # Administrator group
    - id: 4
      name: Admin
      pre: "&1Admin"
      commands:
          - god
          - pvp
          - help
          - motd
          - clear
          - who
          - where
          - kick
          - ban
          - unban
          - unkick
          - who
          - time
          - weather
          - kit
          - item
          - i
          - give
          - clean
          - op
          - kill
          - say
          - tp
          - warp
          - jump
          - list
          - setwarp
          - delwarp
          - home
          - sethome
          - protectinfo
          - afk
          - msg
          - pm
          - spawn
          - top
          - p1
          - p2
          - protect
          - protectpvp
          - protectadd
          - protectrem
          - protectdel
          - protectlock
          - iclean
          - mclean
          - mute
          - scout
          - vkick
          - vban
          - vote
          - lock
          - unlock
      banned_access: true
      build: true
      worldedit: false
      superuser: true
    
    # Server owner
    - id: 5
      name: Owner
      pre: "&4Owner"
      commands:
          - god
          - pvp
          - help
          - motd
          - clear
          - who
          - where
          - kick
          - ban
          - unban
          - unkick
          - who
          - time
          - weather
          - kit
          - item
          - i
          - give
          - clean
          - cleanall
          - op
          - kill
          - say
          - tp
          - warp
          - jump
          - list
          - setwarp
          - delwarp
          - home
          - sethome
          - protectinfo
          - afk
          - msg
          - spawn
          - setspawn
          - top
          - p1
          - p2
          - protect
          - protectpvp
          - protectadd
          - protectrem
          - protectdel
          - protectlock
          - iclean
          - mclean
          - mute
          - scout
          - hide
          - title
          - mob
          - vkick
          - vban
          - vote
          - lock
          - unlock
      banned_access: true
      build: true
      worldedit: true
      superuser: true

# Banned items (cannot create, place, or use)
banned: 7, 8, 9, 10, 11, 46, 49, 51, 52, 90, 325, 326, 327, 342, 343, 328, 333, 79

# Do users spawn in non-god mode by default?
# If not declared, defaults to true
defaultgod: false

# Allow flow of lava
lavaflows: false

# Allow flow of water
waterflows: false

# Allow spread of fire
fireflows: false

# Allow TNT explosions; still allows creeper explosions
allowTNT: false

# Do we allow a compass-item based jump?
compassjump: true

# How often do we clean / save the server? (In minutes)
reload: 15

# Uncomment to enable:
# Sets the world to that specific time of day
# based on Minecraft's time system. Read more:
# Must be between 0 and 24000; 0 is dawn and 12000 is dusk
#permatime: 0

# Uncomment to enable:
# Sets the number of minutes between every time
# the statistical log is written to
logdelay: 1

# Minimum number of votes for a vote to pass
minvotes: 2

# Turn on or off local chat; defaults to false, meaining
# all chat messages are sent globally to all players
localchat: false

# Chat radius; if localchat is on, then only players within
# the senders radius (as defined here as an integer) recieves it
chatradius: 128

# Enable RPG and economy features; if set to true all rpg
# and economy code is enabled
roleplay: false

# A list of messages that are displayed after a certain number of seconds
# Note that "delay" is time between messages and "start" is the initial wait period
messages:
    - message: Please support BasicBukkit, visit code.google.com/p/basicbukki
      delay: 240
      start: 0
      
    - message: "Found a bug? Report it: code.google.com/p/basicbukkit"
      delay: 240
      start: 120

# Kit items
kit:
    - 277 1
    - 278 1
    - 279 1

# Max size of the world (width, length)
size:
    - 1024
    - 1024
