name: BasicBukkit
main: nint22.basicbukkit.BasicBukkit
version: 1.0

commands:
    help:
        description: Prints all commands
        usage: /help [page]
    motd:
        description: Prints the Message of the Day
        usage: /motd
    clear:
        description: Clears the output buffer
        usage: /clear
    where:
        description: Prints your location
        usage: /where
    msg:
        description: Sends a private message to the given player
        usage: /msg <player> <message>
    afk:
        description: Declares yourself as away-from-keyboard; any movement or typing will de-afk you
        usage: /afk
    mute:
        description: Mutes a given player; toggles on and off
        usage: /mute <player>
    
    kick:
        description: Kicks a given player off the server
        usage: /kick <player> [duration in minutes]
    ban:
        description: Bans the given player from the server; requires a reason
        usage: /ban <player> [reason]
    unban:
        description: Removes a player's ban and/or kick
        usage: /unban <player>
    unkick:
        description: Alias of unban; removes a player's ban and/or kick
        usage: /unkick <player>
    who:
        description: List all current players
        usage: /who
    scout:
        description: Randomly and silenty warp to a player to scout them for griefing
        usage: /scout
    iclean:
        description: Removes all items and vehicles in the world
        usage: /iclean
    
    time:
        description: Sets the current time to either day or night
        usage: /time <dawn|day|dusk|night>
    weather:
        description: Sets the current weather
        usage: /weather <dry|wet>
    
    kit:
        description: Gives the player the declared kit
        usage: /kit
    item:
        description: Gives the player the target item
        usage: /item <item ID|keyword> [number, defaults to 64]
    i:
        description: Same as /item
        usage: /i <item ID|keyword> [number, defaults to 64]
    give:
        description: Gives the target player the target item
        usage: /give <player> <item ID|keyword> [number, defaults to 64]
    clean:
        description: Removes all of the user's inventory except the active inventory
        usage: /clean
    cleanall:
        description: Removes all of the user's inventory including the active inventory
        usage: /cleanall
    
    op:
        description: Assigns the target player to the given op rank
        usage: /op <player> [group ID or name]
    
    god:
        description: Toggles invincibility; on by default
        usage: /god
    pvp:
        description: Toggles invincibility; on by default
        usage: /pvp
    kill:
        description: Kills self or the target player
        usage: /kill [player]
    say:
        description: Make a server-wide announcement
        usage: /say <message>
    
    tp:
        description: Teleports self to player 1or target player 1 to player 2
        usage: /tp <player1> [player2]
    warp:
        description: Warps self to given warp or lists warp locations
        usage: /warp [location]
    list:
        description: Same as /warp without arguments
        usage: /list
    setwarp:
        description: Sets the current location as a warp location
        usage: /setwarp <warp name>
    delwarp:
        description: Deletes the given warp name from the warp locations
        usage: /delwarp <warp name>
    home:
        description: Warps user to self home location
        usage: /home
    sethome:
        description: Saves the current location for self's home location
        usage: /sethome
    spawn:
        description: Warps user to spawn
        usage: /spawn
    setspawn:
        description: Saves the current location as default spawn location
        usage: /setspawn
    top:
        description: Warps player to the highest block in the player's column
        usage: /top
    jump:
        description: Warps player to the player's targeted location
        usage: /jump
        
    p1:
        description: Sets the first corner location of a protection volume
        usage: /p1
    p2:
        description: Sets the second corner location of a protection volume
        usage: /p2
    protect:
        description: Protects the given area agains any modifications by non-owners
        usage: /protect <area name>
    protectadd:
        description: Adds player to protected area owners list
        usage: /protectadd <area name> <player>
    protectrem:
        description: Removes player from protected area owners list
        usage: /protectrem <area name> <player>
    protectdel:
        description: Delete the protected area
        usage: /protectdel <area name>
    protectinfo:
        description: Prints off all protected area info. or the one you are in
        usage: /protectinfo
