# ############################################################ #
# 
# BasicBukkit - Basic commands for any new MineCraft server
# Copyright 2011 Core S2 - See License.txt for info
# 
# This source file is developed and maintained by:
# + Jeremy Bridon jbridon@cores2.com
# 
# File: basicbukkit.yml
# Desc: Basic Bukkit's default configuration file.
# 
# ############################################################ #

# Message of the Day
motd:
    Welcome to a BasicBukkit server!
    Please type /help for a list of commands

# Op groups
# Note that groups should ALWAYS be numbered 0, 1, 2, ....
groups:
    
    # Default group
    - id: 0
      name: Guest
      pre: "[&bGuest&f]"
      commands:
          - help
          - who
          - motd
      banned_access: false
    
    # Op group
    - id: 1
      name: OP
      pre: "[&4SemiAdmin&f]"
      commands:
          - help
          - who
          - item
      banned_access: true
    
    # Admin
    - id: 2
      name: Owner
      pre: "[&1Owner&f]"
      commands:
          - help
          - item
          - ban
          - kick
      banned_access: true

# Banned items (cannot create, place, or use)
banned: 0, 7, 8, 9, 10, 11, 46, 51, 52, 90, 325, 326, 327, 342, 343, 328, 333, 79

# Allow flow of lava
lavaflows: false

# Allow flow of water
waterflows: false

# Allow spread of fire
fireflows: false

# Allow TNT explosions
allowTNT: false

# A list of messages that are displayed after a certain number of seconds
# Note that "delay" is time between messages and "start" is the initial wait period
messages:
    - message: Please support BasicBukkit, visit code.google.com/p/basicbukki
      delay: 60
      start: 10
      
    - message: This admin is awesome for using BasicBukkit
      delay: 100
      start: 0

# Kit items
kit:
    - 277 1
    - 278 1
    - 279 1

# Max size of the world (width, length)
size:
    - 256
    - 256
    