# ############################################################ #
# 
# BasicBukkit - Basic commands for any new MineCraft server
# Copyright 2011 Core S2 - See License.txt for info
# 
# This source file is developed and maintained by:
# + Jeremy Bridon jbridon@cores2.com
# 
# File: config_roleplay.yml
# Desc: Basic Bukkit's default configuration file for a
# roleplay server.
# 
# ############################################################ #

# Message of the Day
motd:
    - "Welcome to a Roleplaying BasicBukkit server! V1.1"
    - "&aPlease type /help for a list of commands"
    - "&aFound a bug? Report it at: code.google.com/p/basicbukkit"

# Op groups
# Note that groups should ALWAYS be numbered 0, 1, 2, ....
groups:
    
    # Guest group (can do nothing except observe)
    - id: 0
      name: Beggar
      pre: "Beggar"
      commands:
          - help
          - motd
          - clear
          - who
      banned_access: false
      build: false
      worldedit: false
      
    # Roleplay groups
    - id: 1
      name: Builder
      pre: "Builder"
      commands:
          - help
          - motd
          - clear
          - who
          - lock
          - unlock
          - buy
          - sell
          - price
          - money
          - level
          - kjoin
          - kleave
          - kkick
          - kingdoms
      banned_access: false
      build: true
      worldedit: false
      
    # Roleplay groups
    - id: 2
      name: Soldier
      pre: "Soldier"
      commands:
          - help
          - motd
          - clear
          - who
          - lock
          - unlock
          - buy
          - sell
          - price
          - money
          - level
          - kjoin
          - kleave
          - kkick
          - kingdoms
      banned_access: false
      build: true
      worldedit: false
      
    # Roleplay groups
    - id: 3
      name: Dragoon
      pre: "Dragoon"
      commands:
          - help
          - motd
          - clear
          - who
          - lock
          - unlock
          - buy
          - sell
          - price
          - money
          - level
          - kjoin
          - kleave
          - kkick
          - kingdoms
      banned_access: false
      build: true
      worldedit: false
      
    # Roleplay groups
    - id: 4
      name: Knight
      pre: "Knight"
      commands:
          - help
          - motd
          - clear
          - who
          - lock
          - unlock
          - buy
          - sell
          - price
          - money
          - level
          - kjoin
          - kleave
          - kkick
          - kingdoms
      banned_access: false
      build: true
      worldedit: false
      
    # Roleplay groups
    - id: 5
      name: Bishop
      pre: "Bishop"
      commands:
          - help
          - motd
          - clear
          - who
          - lock
          - unlock
          - buy
          - sell
          - price
          - money
          - level
          - kjoin
          - kleave
          - kkick
          - kingdoms
      banned_access: true
      build: true
      worldedit: false
      
    # Roleplay groups
    - id: 6
      name: King
      pre: "King"
      commands:
          - help
          - motd
          - clear
          - who
          - lock
          - unlock
          - buy
          - sell
          - price
          - money
          - level
          - kjoin
          - kleave
          - kkick
          - kingdoms
      banned_access: true
      build: true
      worldedit: true
      
    # Server owner
    - id: 7
      name: Moderator
      pre: "&4Owner"
      commands:
          - god
          - pvp
          - help
          - motd
          - clear
          - who
          - where
          - kick
          - ban
          - unban
          - unkick
          - who
          - time
          - weather
          - kit
          - item
          - i
          - give
          - clean
          - cleanall
          - op
          - kill
          - say
          - tp
          - warp
          - jump
          - list
          - setwarp
          - delwarp
          - home
          - sethome
          - protectinfo
          - afk
          - msg
          - spawn
          - setspawn
          - top
          - p1
          - p2
          - protect
          - protectpvp
          - protectadd
          - protectrem
          - protectdel
          - iclean
          - mclean
          - mute
          - scout
          - hide
          - title
          - mob
          - vkick
          - vban
          - vote
          - lock
          - unlock
          - money
          - level
          - kjoin
          - kleave
          - kkick
          - kingdoms
          - price
          - buy
          - sell
      banned_access: true
      build: true
      worldedit: true
      
    # Server owner
    - id: 8
      name: Owner
      pre: "&4Owner"
      commands:
          - god
          - pvp
          - help
          - motd
          - clear
          - who
          - where
          - kick
          - ban
          - unban
          - unkick
          - who
          - time
          - weather
          - kit
          - item
          - i
          - give
          - clean
          - cleanall
          - op
          - kill
          - say
          - tp
          - warp
          - jump
          - list
          - setwarp
          - delwarp
          - home
          - sethome
          - protectinfo
          - afk
          - msg
          - spawn
          - setspawn
          - top
          - p1
          - p2
          - protect
          - protectpvp
          - protectadd
          - protectrem
          - protectdel
          - iclean
          - mclean
          - mute
          - scout
          - hide
          - title
          - mob
          - vkick
          - vban
          - vote
          - lock
          - unlock
          - money
          - level
          - kjoin
          - kleave
          - kkick
          - kingdoms
          - price
          - buy
          - sell
      banned_access: true
      build: true
      worldedit: true

# Banned items (cannot create, place, or use)
banned: 7, 8, 9, 10, 11, 46, 49, 51, 52, 90, 325, 326, 327, 342, 343, 328, 333, 79

# Do users spawn in non-god mode by default?
# If not declared, defaults to true
defaultgod: false

# Allow flow of lava
lavaflows: false

# Allow flow of water
waterflows: true

# Allow spread of fire
fireflows: false

# Allow TNT explosions; still allows creeper explosions
allowTNT: true

# Do we allow a compass-item based jump?
compassjump: false

# How often do we clean / save the server? (In minutes)
reload: 5

# Uncomment to enable:
# Sets the world to that specific time of day
# based on Minecraft's time system. Read more:
# Must be between 0 and 24000; 0 is dawn and 12000 is dusk
permatime: 6000

# Uncomment to enable:
# Sets the number of minutes between every time
# the statistical log is written to
logdelay: 1

# Minimum number of votes for a vote to pass
minvotes: 2

# Turn on or off local chat; defaults to false, meaining
# all chat messages are sent globally to all players
localchat: false

# Enable RPG and economy features; if set to true all rpg
# and economy code is enabled
roleplay: true

# A list of messages that are displayed after a certain number of seconds
# Note that "delay" is time between messages and "start" is the initial wait period
messages:
    - message: Please support BasicBukkit, visit code.google.com/p/basicbukki
      delay: 240
      start: 0
      
    - message: "Found a bug? Report it: code.google.com/p/basicbukkit"
      delay: 240
      start: 120

# Kit items
kit:
    - 269 1
    - 270 1
    - 271 1

# Max size of the world (width, length)
size:
    - 1024
    - 1024
