# ############################################################ #
# 
# BasicBukkit - Basic commands for any new MineCraft server
# Copyright 2011 Core S2 - See License.txt for info
# 
# This source file is developed and maintained by:
# + Jeremy Bridon jbridon@cores2.com
# 
# File: basicbukkit.yml
# Desc: Basic Bukkit's default configuration file.
# 
# ############################################################ #

# Message of the Day
motd:
    - "Welcome to a BasicBukkit server! V1.0"
    - "&aPlease type /help for a list of commands"
    - "&aFound a bug? Report it at: code.google.com/p/basicbukkit"

# Op groups
# Note that groups should ALWAYS be numbered 0, 1, 2, ....
groups:
    
    # Guest group (can do nothing except observer)
    - id: 0
      name: Guest
      pre: "[&bGuest&f]"
      commands:
          - help
          - motd
          - clear
          - who
          - where
          - home
          - sethome
          - afk
          - msg
      banned_access: false
      build: false
    
    # Builder group
    - id: 1
      name: Builder
      pre: "[&3Builder&f]"
      commands:
          - god
          - pvp
          - help
          - motd
          - clear
          - who
          - where
          - tp
          - warp
          - jump
          - list
          - setwarp
          - delwarp
          - kit
          - item
          - i
          - clean
          - home
          - sethome
          - afk
          - msg
          - top
      banned_access: false
      build: true
    
    # Trusted group
    - id: 2
      name: Op
      pre: "[&2Op&f]"
      commands:
          - god
          - pvp
          - help
          - motd
          - clear
          - who
          - where
          - kick
          - ban
          - unban
          - who
          - time
          - weather
          - kit
          - item
          - i
          - give
          - clean
          - op
          - kill
          - say
          - tp
          - warp
          - jump
          - list
          - setwarp
          - delwarp
          - home
          - sethome
          - afk
          - msg
          - spawn
          - top
          - p1
          - p2
          - protect
          - protectadd
          - protectrem
          - protectdel
      banned_access: true
      build: true
    
    # Server owner
    - id: 3
      name: Owner
      pre: "[&1Owner&f]"
      commands:
          - god
          - pvp
          - help
          - motd
          - clear
          - who
          - where
          - kick
          - ban
          - unban
          - who
          - time
          - weather
          - kit
          - item
          - i
          - give
          - clean
          - op
          - kill
          - say
          - tp
          - warp
          - jump
          - list
          - setwarp
          - delwarp
          - home
          - sethome
          - afk
          - msg
          - spawn
          - setspawn
          - top
          - p1
          - p2
          - protect
          - protectadd
          - protectrem
          - protectdel
          - iclean
      banned_access: true
      build: true

# Banned items (cannot create, place, or use)
banned: 0, 7, 8, 9, 10, 11, 46, 49, 51, 52, 90, 325, 326, 327, 342, 343, 328, 333, 79

# Allow flow of lava
lavaflows: false

# Allow flow of water
waterflows: false

# Allow spread of fire
fireflows: false

# Allow TNT explosions
allowTNT: false

# A list of messages that are displayed after a certain number of seconds
# Note that "delay" is time between messages and "start" is the initial wait period
messages:
    - message: Please support BasicBukkit, visit code.google.com/p/basicbukki
      delay: 240
      start: 0
      
    - message: "Found a bug? Report it: code.google.com/p/basicbukkit"
      delay: 240
      start: 120

# Kit items
kit:
    - 277 1
    - 278 1
    - 279 1

# Max size of the world (width, length)
size:
    - 1024
    - 1024
